export interface Program {
  slug: string
  name: string
  tagline: string
  description: string
  duration: string
  ageGroup: string
  outcomes: string[]
  curriculum: Array<{ week: number; topic: string; description: string }>
  skillsGained: string[]
  faq: Array<{ question: string; answer: string }>
  image: string
}

export const programs: Record<string, Program> = {
  'student-media-club': {
    slug: 'student-media-club',
    name: 'Student Media Club',
    tagline: 'Build your school\'s creative powerhouse',
    description: 'A weekly hands-on program where students learn journalism, content creation, videography, and digital storytelling while building their school\'s official media presence.',
    duration: '12 weeks',
    ageGroup: '13-18 years',
    outcomes: [
      'Launch school media channel',
      'Publish 20+ professional articles/videos',
      'Develop portfolio pieces',
      'Master media workflows',
    ],
    curriculum: [
      { week: 1, topic: 'Introduction to Journalism', description: 'Learn news fundamentals, interview techniques, and editorial standards.' },
      { week: 2, topic: 'Video Basics', description: 'Camera work, framing, lighting, and basic video editing.' },
      { week: 3, topic: 'Audio & Podcasting', description: 'Recording quality audio, editing, and podcast production.' },
      { week: 4, topic: 'Writing for Digital', description: 'Headlines, social media, SEO basics, and digital storytelling.' },
      { week: 5, topic: 'Photography Fundamentals', description: 'Composition, lighting, and photo editing essentials.' },
      { week: 6, topic: 'Project Assignment', description: 'First major project - students propose and execute.' },
      { week: 7, topic: 'Advanced Editing', description: 'Color grading, transitions, and professional techniques.' },
      { week: 8, topic: 'Social Media Strategy', description: 'Growing audience, analytics, and content calendars.' },
      { week: 9, topic: 'Live Streaming', description: 'Broadcasting events, Q&As, and interactive content.' },
      { week: 10, topic: 'Project Execution', description: 'Students execute second major project.' },
      { week: 11, topic: 'Portfolio Building', description: 'Curating best work and creating professional portfolio.' },
      { week: 12, topic: 'Final Showcase', description: 'Public premiere and reflection on learning.' },
    ],
    skillsGained: ['Videography', 'Journalism', 'Editing', 'Photography', 'Social Media', 'Audio Production', 'Leadership'],
    faq: [
      { question: 'Do students need equipment?', answer: 'No! We provide all professional cameras, microphones, and editing software. Students can use smartphones too.' },
      { question: 'Will this help college applications?', answer: 'Absolutely. Students build professional portfolio pieces and develop leadership experience.' },
      { question: 'How often do they meet?', answer: 'Once per week for 3 hours. We can customize timings to fit school schedules.' },
    ],
    image: '/images/student-media.jpg',
  },
  'school-tv-podcast-studio': {
    slug: 'school-tv-podcast-studio',
    name: 'School TV & Podcast Studio',
    tagline: 'Create professional content that reaches thousands',
    description: 'Students launch and run their school\'s professional video channel and podcast network, learning broadcast production, show hosting, and audience engagement.',
    duration: '16 weeks',
    ageGroup: '14-18 years',
    outcomes: [
      'Launch 2+ podcasts',
      'Produce 16 professional episodes',
      'Build 1000+ subscriber base',
      'Generate branded content',
    ],
    curriculum: [
      { week: 1, topic: 'Show Concept Development', description: 'Ideation, format, audience research, and positioning.' },
      { week: 2, topic: 'Studio Setup', description: 'Professional audio setup, lighting, and green screen basics.' },
      { week: 3, topic: 'Hosting & Presentation', description: 'On-camera presence, voice control, and speaking skills.' },
      { week: 4, topic: 'Interview Techniques', description: 'Conducting engaging interviews, research, and questioning.' },
      { week: 5, topic: 'Audio Production', description: 'Professional podcast editing, mixing, and mastering.' },
      { week: 6, topic: 'Video Production', description: 'Multi-camera shooting, transitions, graphics, and effects.' },
      { week: 7, topic: 'Episode 1 - Production', description: 'Students produce first episode with full crew roles.' },
      { week: 8, topic: 'Distribution & Publishing', description: 'Upload to Spotify, YouTube, distribution platforms.' },
      { week: 9, topic: 'Audience Growth', description: 'Social media promotion, cross-promotion, engagement tactics.' },
      { week: 10, topic: 'Sponsorships & Monetization', description: 'Understanding media economics and ad integration.' },
      { week: 11, topic: 'Guest Management', description: 'Booking, prepping, and interviewing notable guests.' },
      { week: 12, topic: 'Analytics & Optimization', description: 'Data-driven decisions, audience metrics, feedback.' },
      { week: 13, topic: 'Season Content Calendar', description: 'Planning full season, maintaining consistency.' },
      { week: 14, topic: 'Advanced Production', description: 'Multi-show coordination, complex editing, graphics.' },
      { week: 15, topic: 'Networking & Collaborations', description: 'Guest swaps, cross-promotions, industry connections.' },
      { week: 16, topic: 'Launch Event & Reflection', description: 'Public premiere and celebration of achievement.' },
    ],
    skillsGained: ['Broadcasting', 'Hosting', 'Audio Production', 'Video Production', 'Audience Growth', 'Public Speaking'],
    faq: [
      { question: 'How many students participate?', answer: 'Typically 8-12 students with different roles: hosts, producers, editors, and promotion managers.' },
      { question: 'Will this be profitable?', answer: 'While not the main goal, successful shows can generate small revenue through ads after reaching certain subscriber counts.' },
      { question: 'What if we don\'t have studio space?', answer: 'We can set up in any classroom, cafeteria, or even outdoor spaces. Flexibility is built into our model.' },
    ],
    image: '/images/podcast-studio.jpg',
  },
  'filmmaking-editing': {
    slug: 'filmmaking-editing',
    name: 'Filmmaking & Editing',
    tagline: 'Tell stories that move people',
    description: 'An intensive program where students learn cinematography, directing, and post-production while creating a professional short film.',
    duration: '14 weeks',
    ageGroup: '14-18 years',
    outcomes: [
      'Create 3-5 minute short film',
      'Master directing fundamentals',
      'Professional color grading',
      'Film festival submission ready',
    ],
    curriculum: [
      { week: 1, topic: 'Film Language Basics', description: 'Shot types, angles, movement, pacing, and storytelling through visuals.' },
      { week: 2, topic: 'Directing & Vision', description: 'Developing directorial voice, visual style, and creative decisions.' },
      { week: 3, topic: 'Cinematography Fundamentals', description: 'Camera operation, exposure, focus, and composition mastery.' },
      { week: 4, topic: 'Lighting Design', description: 'Three-point lighting, color temperature, and mood creation through light.' },
      { week: 5, topic: 'Scriptwriting for Film', description: 'Narrative structure, dialogue, visual descriptions, and formatting.' },
      { week: 6, topic: 'Pre-production Planning', description: 'Storyboarding, shot lists, location scouting, and production design.' },
      { week: 7, topic: 'Production Week 1', description: 'Shooting principal photography with crew roles.' },
      { week: 8, topic: 'Production Week 2', description: 'Reshoots, B-roll collection, and pickups.' },
      { week: 9, topic: 'Non-linear Editing', description: 'DaVinci Resolve or Premiere: cutting, pacing, and timeline management.' },
      { week: 10, topic: 'Color Grading & VFX', description: 'Professional color correction, grading, and visual effects integration.' },
      { week: 11, topic: 'Sound Design & Mix', description: 'Dialogue, music, effects, and professional audio mixing.' },
      { week: 12, topic: 'Motion Graphics & Titles', description: 'Creating titles, credits, and animated elements.' },
      { week: 13, topic: 'Finishing & Delivery', description: 'Final exports, subtitles, and format specifications.' },
      { week: 14, topic: 'Festival Prep & Premiere', description: 'Submission materials, premiere screening, and celebration.' },
    ],
    skillsGained: ['Cinematography', 'Directing', 'Editing', 'Color Grading', 'Sound Design', 'Visual Storytelling'],
    faq: [
      { question: 'Do we need professional cameras?', answer: 'No. Smartphones or entry-level DSLRs work great. We focus on storytelling over gear.' },
      { question: 'Can we submit to real film festivals?', answer: 'Yes! Students\' films are absolutely festival-ready and can compete against professional entries.' },
      { question: 'How much outdoor filming is involved?', answer: 'Varies by script. We can shoot indoors, outdoors, or mix both based on creative vision.' },
    ],
    image: '/images/filmmaking.jpg',
  },
  'ai-content-creation': {
    slug: 'ai-content-creation',
    name: 'AI-Driven Content Creation',
    tagline: 'Master AI tools for modern content',
    description: 'Students learn to leverage ChatGPT, Midjourney, text-to-speech, and other AI tools to create marketing content, social media, and multimedia projects at scale.',
    duration: '10 weeks',
    ageGroup: '13-18 years',
    outcomes: [
      'Create 100+ pieces of AI content',
      'Understand AI capabilities and ethics',
      'Build portfolio with AI-created pieces',
      'Develop AI content strategy',
    ],
    curriculum: [
      { week: 1, topic: 'AI Fundamentals', description: 'What is AI, how it works, limitations, and ethical considerations.' },
      { week: 2, topic: 'ChatGPT Mastery', description: 'Prompting techniques, workflows, and content generation at scale.' },
      { week: 3, topic: 'AI Image Generation', description: 'Midjourney, DALL-E, Stable Diffusion, and visual creativity.' },
      { week: 4, topic: 'Audio & Voice AI', description: 'Text-to-speech, voice cloning, podcast production with AI.' },
      { week: 5, topic: 'Video AI', description: 'AI video generation, deepfakes ethics, and automated editing.' },
      { week: 6, topic: 'Content Strategy', description: 'Building AI-powered content calendars and workflows.' },
      { week: 7, topic: 'Social Media at Scale', description: 'Creating 30 days of Instagram, TikTok, and LinkedIn content.' },
      { week: 8, topic: 'Branding with AI', description: 'Logo design, marketing materials, and brand consistency.' },
      { week: 9, topic: 'AI Ethics & Safety', description: 'Responsible AI use, misinformation, copyright, and attribution.' },
      { week: 10, topic: 'Portfolio & Pitching', description: 'Showcase AI projects and pitch to potential clients or colleges.' },
    ],
    skillsGained: ['AI Prompting', 'Content Strategy', 'Visual Design', 'Social Media', 'AI Ethics', 'Automation'],
    faq: [
      { question: 'Is AI replacing human creativity?', answer: 'Not at all. AI is a tool that amplifies human creativity when used thoughtfully. We teach students to blend AI efficiency with human judgment.' },
      { question: 'Are there copyright issues with AI?', answer: 'Yes, this is evolving. We teach students about current guidelines, proper attribution, and ethical considerations.' },
      { question: 'Will this help with career prospects?', answer: 'Absolutely. Every industry is adopting AI. Students with hands-on AI experience are highly sought after.' },
    ],
    image: '/images/ai-content.jpg',
  },
  'teacher-training': {
    slug: 'teacher-training',
    name: 'Teacher Training Program',
    tagline: 'Empower educators to teach creative skills',
    description: 'Professional development for teachers to integrate media creation into curriculum and facilitate student-led projects.',
    duration: '8 weeks',
    ageGroup: 'Educators',
    outcomes: [
      'Get certified facilitator',
      'Learn project frameworks',
      'Build school media club',
      'Ongoing support & resources',
    ],
    curriculum: [
      { week: 1, topic: 'Program Overview & Pedagogy', description: 'Understanding project-based learning and creative pedagogy.' },
      { week: 2, topic: 'Technical Skills Immersion', description: 'Hands-on with cameras, audio, editing software, and platforms.' },
      { week: 3, topic: 'Facilitation Techniques', description: 'Managing student groups, giving feedback, and building confidence.' },
      { week: 4, topic: 'Curriculum Integration', description: 'Connecting media to existing subjects and standards.' },
      { week: 5, topic: 'Safety & Ethics', description: 'Student safety, consent, privacy, and responsible content.' },
      { week: 6, topic: 'Assessment & Portfolios', description: 'Evaluating creative work and portfolio development.' },
      { week: 7, topic: 'Troubleshooting & Support', description: 'Common challenges, technical issues, and solutions.' },
      { week: 8, topic: 'Certification & Launch', description: 'Final certification and launching school program.' },
    ],
    skillsGained: ['Facilitation', 'Technical Skills', 'Curriculum Design', 'Assessment', 'Student Leadership'],
    faq: [
      { question: 'Do I need technical background?', answer: 'No! We provide complete training regardless of experience level.' },
      { question: 'How much time commitment?', answer: 'About 5-8 hours per week during the 8-week training, then ongoing support.' },
      { question: 'Will my students want to participate?', answer: 'Most schools see 50-100+ student applications. This stuff is engaging!' },
    ],
    image: '/images/teacher-training.jpg',
  },
  'parent-workshops': {
    slug: 'parent-workshops',
    name: 'Parent Workshops',
    tagline: 'Understand media creation with your child',
    description: 'Interactive workshops for parents to learn alongside their children, understand the program, and support media literacy at home.',
    duration: 'Varies',
    ageGroup: 'Parents & Guardians',
    outcomes: [
      'Understand media literacy',
      'Support child\'s creative journey',
      'Learn photography basics',
      'Appreciate student work',
    ],
    curriculum: [
      { week: 1, topic: 'Media Literacy for Parents', description: 'Understanding digital media, consumption, and creation.' },
      { week: 2, topic: 'Your Child\'s Creative Journey', description: 'What they\'re learning, how to support them at home.' },
      { week: 3, topic: 'Hands-On Workshop', description: 'Parents create their own short video or photo project.' },
      { week: 4, topic: 'Q&A with Student Showcase', description: 'Students present work, Q&A session, celebration.' },
    ],
    skillsGained: ['Media Literacy', 'Digital Citizenship', 'Parental Support'],
    faq: [
      { question: 'Do I need tech skills?', answer: 'Not at all. Workshops are beginner-friendly and very hands-on.' },
      { question: 'Will I see my child\'s work?', answer: 'Yes! Student showcase is part of the workshops.' },
      { question: 'How much does it cost?', answer: 'Workshops are included with student enrollment.' },
    ],
    image: '/images/parent-workshop.jpg',
  },
}
